name: Deploy Node.js to AWS EC2

on:
   push:
      branches:
         - master # Deploy when pushing to main

jobs:
   deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout Repository
           uses: actions/checkout@v3

         - name: Setup SSH Key
           run: |
              echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
              chmod 600 private_key.pem

         - name: Deploy to EC2
           run: |
              ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
              cd demo-node
              git pull origin master
              npm install
              pm2 restart all || pm2 start server.js --name nodeapp
              EOF
